In [1]:
# Load Libraries
import pandas as pd
import numpy as np

In [4]:
# Load dataset
df = pd.read_csv('weatherHistory.csv') 
df.head()

,Formatted Date,Summary,Precip Type,Temperature (C),Apparent Temperature (C),Humidity,Wind Speed (km/h),Wind Bearing (degrees),Visibility (km),Loud Cover,Pressure (millibars),Daily Summary
0,2006-04-01 00:00:00.000 +0200,Partly Cloudy,rain,9.472222,7.388889,0.89,14.1197,251.0,15.8263,0.0,1015.13,Partly cloudy throughout the day.
1,2006-04-01 01:00:00.000 +0200,Partly Cloudy,rain,9.355556,7.227778,0.86,14.2646,259.0,15.8263,0.0,1015.63,Partly cloudy throughout the day.
2,2006-04-01 02:00:00.000 +0200,Mostly Cloudy,rain,9.377778,9.377778,0.89,3.9284,204.0,14.9569,0.0,1015.94,Partly cloudy throughout the day.
3,2006-04-01 03:00:00.000 +0200,Partly Cloudy,rain,8.288889,5.944444,0.83,14.1036,269.0,15.8263,0.0,1016.41,Partly cloudy throughout the day.
4,2006-04-01 04:00:00.000 +0200,Mostly Cloudy,rain,8.755556,6.977778,0.83,11.0446,259.0,15.8263,0.0,1016.51,Partly cloudy throughout the day.

## **Level = Easy**

1.	Load and Inspect:
    -	Load the CSV file into a pandas DataFrame and display the first 5 rows.
    -	Display the summary statistics of the DataFrame.

In [5]:
df.head(5)

,Formatted Date,Summary,Precip Type,Temperature (C),Apparent Temperature (C),Humidity,Wind Speed (km/h),Wind Bearing (degrees),Visibility (km),Loud Cover,Pressure (millibars),Daily Summary
0,2006-04-01 00:00:00.000 +0200,Partly Cloudy,rain,9.472222,7.388889,0.89,14.1197,251.0,15.8263,0.0,1015.13,Partly cloudy throughout the day.
1,2006-04-01 01:00:00.000 +0200,Partly Cloudy,rain,9.355556,7.227778,0.86,14.2646,259.0,15.8263,0.0,1015.63,Partly cloudy throughout the day.
2,2006-04-01 02:00:00.000 +0200,Mostly Cloudy,rain,9.377778,9.377778,0.89,3.9284,204.0,14.9569,0.0,1015.94,Partly cloudy throughout the day.
3,2006-04-01 03:00:00.000 +0200,Partly Cloudy,rain,8.288889,5.944444,0.83,14.1036,269.0,15.8263,0.0,1016.41,Partly cloudy throughout the day.
4,2006-04-01 04:00:00.000 +0200,Mostly Cloudy,rain,8.755556,6.977778,0.83,11.0446,259.0,15.8263,0.0,1016.51,Partly cloudy throughout the day.

2.	Basic Analysis:
    -	Calculate the mean and median temperature.
    -	Find the minimum and maximum wind speed.

In [9]:
df.columns

Index(['Formatted Date', 'Summary', 'Precip Type', 'Temperature (C)',
       'Apparent Temperature (C)', 'Humidity', 'Wind Speed (km/h)',
       'Wind Bearing (degrees)', 'Visibility (km)', 'Loud Cover',
       'Pressure (millibars)', 'Daily Summary'],
      dtype='object')

In [15]:
mean_tempertaure = df['Temperature (C)'].mean()
print(f"Mean of Temperature: {mean_tempertaure}")

median_tempertaure = df['Temperature (C)'].median()
print(f'Median of Temperature: {median_tempertaure}')

Mean of Temperature: 11.93267843751188
Median of Temperature: 12.0

3.	Filtering Data:
    -	Filter the data to include only days with a temperature above 25°C.
    -	Find all entries where the humidity is above 90%.

In [20]:
# Filter the data to include only days with a temperature above 25°C.
df[df['Temperature (C)'] < 25]

,Formatted Date,Summary,Precip Type,Temperature (C),Apparent Temperature (C),Humidity,Wind Speed (km/h),Wind Bearing (degrees),Visibility (km),Loud Cover,Pressure (millibars),Daily Summary
0,2006-04-01 00:00:00.000 +0200,Partly Cloudy,rain,9.472222,7.388889,0.89,14.1197,251.0,15.8263,0.0,1015.13,Partly cloudy throughout the day.
1,2006-04-01 01:00:00.000 +0200,Partly Cloudy,rain,9.355556,7.227778,0.86,14.2646,259.0,15.8263,0.0,1015.63,Partly cloudy throughout the day.
2,2006-04-01 02:00:00.000 +0200,Mostly Cloudy,rain,9.377778,9.377778,0.89,3.9284,204.0,14.9569,0.0,1015.94,Partly cloudy throughout the day.
3,2006-04-01 03:00:00.000 +0200,Partly Cloudy,rain,8.288889,5.944444,0.83,14.1036,269.0,15.8263,0.0,1016.41,Partly cloudy throughout the day.
4,2006-04-01 04:00:00.000 +0200,Mostly Cloudy,rain,8.755556,6.977778,0.83,11.0446,259.0,15.8263,0.0,1016.51,Partly cloudy throughout the day.
...,...,...,...,...,...,...,...,...,...,...,...,...
96439,2016-09-09 10:00:00.000 +0200,Partly Cloudy,rain,22.872222,22.872222,0.59,6.4239,49.0,16.1000,0.0,1015.65,Partly cloudy starting in the morning.
96449,2016-09-09 20:00:00.000 +0200,Partly Cloudy,rain,24.583333,24.583333,0.48,10.0947,20.0,15.5526,0.0,1015.16,Partly cloudy starting in the morning.
96450,2016-09-09 21:00:00.000 +0200,Partly Cloudy,rain,22.038889,22.038889,0.56,8.9838,30.0,16.1000,0.0,1015.66,Partly cloudy starting in the morning.
96451,2016-09-09 22:00:00.000 +0200,Partly Cloudy,rain,21.522222,21.522222,0.60,10.5294,20.0,16.1000,0.0,1015.95,Partly cloudy starting in the morning.
96452,2016-09-09 23:00:00.000 +0200,Partly Cloudy,rain,20.438889,20.438889,0.61,5.8765,39.0,15.5204,0.0,1016.16,Partly cloudy starting in the morning.

In [21]:
# Find all entries where the humidity is above 90%.
df[df['Humidity'] > 0.9]

,Formatted Date,Summary,Precip Type,Temperature (C),Apparent Temperature (C),Humidity,Wind Speed (km/h),Wind Bearing (degrees),Visibility (km),Loud Cover,Pressure (millibars),Daily Summary
6,2006-04-01 06:00:00.000 +0200,Partly Cloudy,rain,7.733333,5.522222,0.95,12.3648,259.0,9.9820,0.0,1016.72,Partly cloudy throughout the day.
53,2006-04-11 05:00:00.000 +0200,Overcast,rain,10.694444,10.694444,0.95,10.4006,161.0,6.6976,0.0,1006.59,Foggy in the evening.
54,2006-04-11 06:00:00.000 +0200,Mostly Cloudy,rain,11.111111,11.111111,0.93,12.0106,140.0,5.9731,0.0,1006.34,Foggy in the evening.
55,2006-04-11 07:00:00.000 +0200,Mostly Cloudy,rain,11.111111,11.111111,0.93,9.2092,103.0,10.8031,0.0,1006.09,Foggy in the evening.
67,2006-04-11 19:00:00.000 +0200,Foggy,rain,8.800000,5.294444,0.99,26.5006,339.0,2.6565,0.0,1004.99,Foggy in the evening.
...,...,...,...,...,...,...,...,...,...,...,...,...
96407,2016-09-08 02:00:00.000 +0200,Partly Cloudy,rain,16.150000,16.150000,0.93,0.3703,160.0,15.1501,0.0,1019.06,Partly cloudy starting overnight.
96408,2016-09-08 03:00:00.000 +0200,Partly Cloudy,rain,15.488889,15.488889,0.93,3.0268,359.0,15.1340,0.0,1018.63,Partly cloudy starting overnight.
96409,2016-09-08 04:00:00.000 +0200,Partly Cloudy,rain,16.066667,16.066667,0.93,3.2039,19.0,15.1340,0.0,1018.24,Partly cloudy starting overnight.
96433,2016-09-09 04:00:00.000 +0200,Clear,rain,15.011111,15.011111,0.93,3.2039,341.0,15.8263,0.0,1014.37,Partly cloudy starting in the morning.
96435,2016-09-09 06:00:00.000 +0200,Clear,rain,13.872222,13.872222,0.93,4.7495,0.0,15.8263,0.0,1014.66,Partly cloudy starting in the morning.

4.	Date Range:
    -	Determine the range of dates covered in the dataset.

In [28]:
df.columns
min_date = df['Formatted Date'].min()
print(f"Min Date: {min_date}")
max_date = df['Formatted Date'].max()
print(f"Max Date: {max_date}")

print(f"\nRange of date covered in dataset are from {max_date} to {min_date}")

Min Date: 2006-01-01 00:00:00.000 +0100
Max Date: 2016-12-31 23:00:00.000 +0100

Range of date covered in dataset are from 2016-12-31 23:00:00.000 +0100 to 2006-01-01 00:00:00.000 +0100

## **Level = Intermediate**

1.	Grouping and Aggregation:
    -	Group the data by Precip Type and calculate the average temperature and humidity for each group.
    -	Find the total number of records for each Precip Type.

In [29]:
df.columns

Index(['Formatted Date', 'Summary', 'Precip Type', 'Temperature (C)',
       'Apparent Temperature (C)', 'Humidity', 'Wind Speed (km/h)',
       'Wind Bearing (degrees)', 'Visibility (km)', 'Loud Cover',
       'Pressure (millibars)', 'Daily Summary'],
      dtype='object')

In [35]:
# Group the data by Precip Type and calculate the average temperature and humidity for each group
display(df.groupby('Precip Type')[['Temperature (C)']].mean())
display(df.groupby('Precip Type')[['Humidity']].mean())

             Temperature (C)
Precip Type
rain               13.852989
snow               -3.270885

             Humidity
Precip Type
rain         0.718699
snow         0.863263

In [43]:
# Find the total number of records for each Precip Type.
df['Precip Type'].value_counts()

Precip Type
rain    85224
snow    10712
Name: count, dtype: int64

2.	Correlation Analysis:
    -	Calculate the correlation matrix for temperature, apparent temperature, humidity, and wind speed.

In [44]:
df.columns

Index(['Formatted Date', 'Summary', 'Precip Type', 'Temperature (C)',
       'Apparent Temperature (C)', 'Humidity', 'Wind Speed (km/h)',
       'Wind Bearing (degrees)', 'Visibility (km)', 'Loud Cover',
       'Pressure (millibars)', 'Daily Summary'],
      dtype='object')

In [46]:
# Calculate the correlation matrix for temperature, apparent temperature, humidity, and wind speed
correlation = df[['Temperature (C)','Apparent Temperature (C)','Humidity','Wind Speed (km/h)']].corr()
correlation

,Temperature (C),Apparent Temperature (C),Humidity,Wind Speed (km/h)
Temperature (C),1.000000,0.992629,-0.632255,0.008957
Apparent Temperature (C),0.992629,1.000000,-0.602571,-0.056650
Humidity,-0.632255,-0.602571,1.000000,-0.224951
Wind Speed (km/h),0.008957,-0.056650,-0.224951,1.000000

3.	Handling Missing Values:
    -	Identify the columns with missing values and the number of missing entries in each.
    -	Fill the missing values using an appropriate method (e.g., forward fill, backward fill, mean).

In [48]:
# Identify the columns with missing values and the number of missing entries in each.
df.isnull()
df.isnull().sum()

Formatted Date                0
Summary                       0
Precip Type                 517
Temperature (C)               0
Apparent Temperature (C)      0
Humidity                      0
Wind Speed (km/h)             0
Wind Bearing (degrees)        0
Visibility (km)               0
Loud Cover                    0
Pressure (millibars)          0
Daily Summary                 0
dtype: int64

In [53]:
# Fill the missing values using an appropriate method (e.g., forward fill, backward fill, mean).

df.ffill(inplace=True)  # Forward fill in all columns
df.bfill(inplace = True)    # Backword fill in all columns
df.isnull().sum()   # Check sum of null values

Formatted Date              0
Summary                     0
Precip Type                 0
Temperature (C)             0
Apparent Temperature (C)    0
Humidity                    0
Wind Speed (km/h)           0
Wind Bearing (degrees)      0
Visibility (km)             0
Loud Cover                  0
Pressure (millibars)        0
Daily Summary               0
dtype: int64

4.	Data Visualization:
    -	Plot the daily temperature and humidity on the same plot.
    -	Create a scatter plot of temperature vs. apparent temperature.

5.	Weather Summary Analysis:
    -	Count the number of unique daily summaries.
    -	Identify the most common daily summary in the dataset.
    -	Find the daily summary that corresponds to the highest average temperature.

6.	Advanced Filtering:
    -	Filter the data to include only days with visibility below 10 km and wind speed above 20 km/h.
    -	Identify the day with the highest pressure and describe the weather conditions on that day.